version: '3'
services:
  hello-world:
    build: ./hello-world
    volumes:
      - ./hello-world:/home/node/html
      - ./hello-world/Dockerfile:/home/node/html/Dockerfile:ro
    ports:
      - '8082:8081'
  contact-card:
    build: ./contact-card
    volumes:
      - ./contact-card:/home/node/html
      - ./contact-card/Dockerfile:/home/node/html/Dockerfile:ro
    ports:
      - '8083:8081'
  elmsln-team:
    build: ./elmsln-team
    volumes:
      - ./elmsln-team:/home/node/html
      - ./elmsln-team/Dockerfile:/home/node/html/Dockerfile:ro
    ports:
      - '8084:8081'