version: '3'
services:
  lrndev:
    image: heymp/lrndeveloper
    volumes:
      - .:/home/node/html
  hello-world:
    image: heymp/lrndeveloper
    volumes:
      - ./hello-world:/home/node/html
    ports:
      - '8082:8082'
    command: polymer serve -p 8082 -H 0.0.0.0