version: '3'
services:
  api:
    build: ./api
    volumes:
      - ./api:/home/node/api
      - /api/node_modules
    ports:
      - "3000:3000"
  hello-world:
    build: ./hello-world
    volumes:
      - ./hello-world:/home/node/html
      - ./hello-world/Dockerfile:/home/node/html/Dockerfile:ro
    ports:
      - '8082:8081'
  awesome-explosion:
    build: ./awesome-explosion
    volumes:
      - ./awesome-explosion:/home/node/html
      - ./awesome-explosion/Dockerfile:/home/node/html/Dockerfile:ro
  youtube-searcher:
    build: ./youtube-searcher
    volumes:
      - ./youtube-searcher:/home/node/html
      - ./youtube-searcher/Dockerfile:/home/node/html/Dockerfile:ro
    ports:
      - '8084:8081'